export const GET_DATA_USERS_START = 'GET_DATA_USERS_START';
export const GET_DATA_USERS_SUCCESS = 'GET_DATA_USERS_SUCCESS';
export const GET_DATA_USERS_ERROR = 'GET_DATA_USERS_ERROR';

export const LOGIN_USERS_START = 'LOGIN_USERS_START';
export const LOGIN_USERS_SUCCESS = 'LOGIN_USERS_SUCCESS';
export const LOGIN_USERS_ERROR = 'LOGIN_USERS_ERROR';

export const CREATE_USERS_START = 'CREATE_USERS_START ';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS ';
export const CREATE_USERS_ERROR = 'CREATE_USERS_ERROR ';

export const DELETE_USERS_START = 'DELETE_USERS_START ';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS ';
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR ';

export const UPDATE_USERS_START = 'UPDATE_USERS_START ';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS ';
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR ';

export const IMAGE_GET_START = 'IMAGE_GET_START ';
export const IMAGE_GET_SUCCESS = 'IMAGE_GET_SUCCESS ';
export const IMAGE_GET_ERROR = 'IMAGE_GET_ERROR ';

export const IMAGE_UPLOAD_START = 'IMAGE_UPLOAD_START ';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS ';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR ';

export const IMAGE_DELETE_START = 'IMAGE_DELETE_START ';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS ';
export const IMAGE_DELETE_ERROR = 'IMAGE_DELETE_ERROR ';
